" Basic Settings
set number              " Show line numbers
set relativenumber      " Relative line numbers for easier jumping
set tabstop=4           " One Tab = 4 spaces
set shiftwidth=4        " Indentation amount for >> and <<
set expandtab           " Convert tabs to spaces
set autoindent          " Copy indent from current line when starting a new one
set smartindent         " Do smart autoindenting when starting a new line
set cursorline          " Highlight the line where the cursor is located
syntax on               " Enable syntax highlighting

" Filetype recognition
filetype plugin indent on

" Automatic Header for Bash scripts
" When creating a new .sh file, insert Shebang and move cursor to the end
autocmd BufNewFile *.sh 0put = '#!/bin/bash' | $put = '' | startinsert
